### ISSUE TITLE
misc tests

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier-regression-testing#268]

**Comment by fisker** [comment]
Run #14077 vs 2.8.1

**Comment by thorn0** [comment]
Run thorn0/prettier#callAncestor-7976 vs #14077

**Comment by fisker** [comment]
Run #14111 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #14171 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #14171 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #14189 vs prettier/prettier@next

**Comment by thorn0** [comment]
Run #14192 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #14259 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #14259 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #14313 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #14402 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next

**Comment by fisker** [comment]
Run #13819 vs prettier/prettier@next
