### ISSUE TITLE
for 13735 (Print `ChainExpression`)

### ISSUE THREAD

**Issue by fisker** [prettier/prettier-regression-testing#293]

**Comment by fisker** [comment]
run #13735 vs prettier/prettier#next

**Comment by fisker** [comment]
run #13735 vs prettier/prettier#next

**Comment by liuxingbaoyu** [comment]
https://github.com/prettier/prettier-regression-testing/blob/52c0c63fda5f147594a1544fedfb1aff1771a24e/projects.json#L2-L7
Is `glob` something to be processed? We should currently only have a few js files.

**Comment by fisker** [comment]
run #13735 vs prettier/prettier#next

**Comment by fisker** [comment]
Added ts files to test https://github.com/prettier/prettier-regression-testing/commit/c2b83c4aeadb28009bf3061ec61b4cfbabd3e947

Thanks!
