### ISSUE TITLE
pr 10296 -- refactoring decorators

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier-regression-testing#39]

**Comment by thorn0** [comment]
run #10296

**Comment by thorn0** [comment]
I guess none of the repos uses decorators anyway. We need to add some project with decorators.

**Comment by fisker** [comment]
I proposed support `run alternativeVersionPrettier vs originalVersionPrettier on project1 project2 ... projectN` in #15, but master branch didn't implement.
