### ISSUE TITLE
misc tests

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier-regression-testing#41]
One-off tests for simple issues.

**Comment by thorn0** [comment]
run #10457

**Comment by thorn0** [comment]
run #10032

**Comment by thorn0** [comment]
run thorn0/prettier#couldGroupArg-experiments

**Comment by thorn0** [comment]
run #10495

**Comment by thorn0** [comment]
run #10517

**Comment by sosukesuzuki** [comment]
run #10702

**Comment by thorn0** [comment]
run #13115

**Comment by thorn0** [comment]
run #13115 vs prettier/prettier#67efa96da68a4bae5620db0b2cbc4efd8b18b4df

**Comment by thorn0** [comment]
run thorn0/prettier@call-args VS prettier/prettier@next

**Comment by thorn0** [comment]
run thorn0/prettier@call-args VS prettier/prettier@6afb16ba15dfaf5ddea0d96549182db0314836dc

**Comment by thorn0** [comment]
run thorn0/prettier@call-args VS thorn0/prettier@fix-show-doc

**Comment by thorn0** [comment]
run thorn0/prettier@call-args VS prettier/prettier@67e1348df16316f3bd373d4419f5a620cde79c15

**Comment by thorn0** [comment]
run thorn0/prettier#call-args VS prettier/prettier#fe1c28e

**Comment by thorn0** [comment]
run #13341 VS prettier/prettier#fe1c28e

**Comment by thorn0** [comment]
run #13341 VS prettier/prettier#fe1c28e

**Comment by thorn0** [comment]
run #13341 VS prettier/prettier#fe1c28e

**Comment by thorn0** [comment]
run #13341 VS prettier/prettier#next

**Comment by thorn0** [comment]
run #13359 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13341 VS prettier/prettier#next

**Comment by thorn0** [comment]
run #13341 VS thorn0/prettier#6369b4020f5ee8

**Comment by thorn0** [comment]
run thorn0/prettier#6369b4020f5ee8 VS prettier/prettier#next

**Comment by fisker** [comment]
run #13343 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13391 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13391 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13396 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13396 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13410 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13438 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13532 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13532 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13532 vs prettier/prettier#next

**Comment by thorn0** [comment]
run #13532 vs prettier/prettier#next
