### ISSUE TITLE
2.3 regression checking

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier-regression-testing#44]
https://github.com/prettier/prettier/issues/10537

**Comment by thorn0** [comment]
run prettier/prettier#main vs 2.2.1

**Comment by fisker** [comment]
run prettier/prettier#main vs 2.2.1

**Comment by thorn0** [comment]
run prettier/prettier#main vs 2.2.1

**Comment by thorn0** [comment]
run prettier/prettier#main vs 2.2.1

**Comment by fisker** [comment]
Personally, I prefer the old one even it's "simple"

```diff
-      const {
-        startBindingElement,
-        endBindingElement,
-      } = appState.editingLinearElement;
+      const { startBindingElement, endBindingElement } =
+        appState.editingLinearElement;

-    let {
-      elements: nextElements,
-      appState: nextAppState,
-    } = deleteSelectedElements(elements, appState);
+    let { elements: nextElements, appState: nextAppState } =
+      deleteSelectedElements(elements, appState);
```

**Comment by thorn0** [comment]
@fisker  see https://github.com/prettier/prettier/pull/10643#issuecomment-813771051

It's better not to break a simple destructuring to make the chance higher for the RHS to break.

**Comment by thorn0** [comment]
E.g. this diff is actually bad:
```diff
-  const {titleAnchor, titleAngle: ta, titleOrient} = getHeaderProperties(
-    ['titleAnchor', 'titleAngle', 'titleOrient'],
-    facetFieldDef.header,
-    config,
-    channel
-  );
+  const {
+    titleAnchor,
+    titleAngle: ta,
+    titleOrient
+  } = getHeaderProperties(['titleAnchor', 'titleAngle', 'titleOrient'], facetFieldDef.header, config, channel);
```

**Comment by maogongzi** [comment]
> E.g. this diff is actually bad:
> 
> ```diff
> -  const {titleAnchor, titleAngle: ta, titleOrient} = getHeaderProperties(
> -    ['titleAnchor', 'titleAngle', 'titleOrient'],
> -    facetFieldDef.header,
> -    config,
> -    channel
> -  );
> +  const {
> +    titleAnchor,
> +    titleAngle: ta,
> +    titleOrient
> +  } = getHeaderProperties(['titleAnchor', 'titleAngle', 'titleOrient'], facetFieldDef.header, config, channel);
> ```

```js
const {
  titleAnchor,
  titleAngle: ta,
  titleOrient
} = getHeaderProperties(
  ['titleAnchor', 'titleAngle', 'titleOrient'],
  facetFieldDef.header,
  config,
  channel
);
```

looks good to me :) and for the sake of an intuitive Git diff output, it might be good to put attributes on separated lines.

**Comment by thorn0** [comment]
@maogongzi  That's exactly how it's printed with `--print-width 80`. Vega-Lite uses 120, and this case is a good illustration of why this is a bad idea.

**Comment by thorn0** [comment]
run prettier/prettier#main vs 2.2.1
